version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Use a Python 3.8 environment
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r Terrorism_Analysis_Project/requirements.txt
      - run:
          name: Run unit tests
          command: python -m unittest discover -s Terrorism_Analysis_Project/Tests
workflows:
  version: 2
  test-and-build:
    jobs:
      - test
