version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Set PYTHONPATH
          command: export PYTHONPATH=$PYTHONPATH:$PWD/Terrorism_Analysis_Project
      - run:
          name: Run tests
          command: python -m unittest discover -s Tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
